### ISSUE TITLE
The `send_offsets `and `recv_offsets ` returned by the function `compute_scatter_from_owner_counts`

### ISSUE THREAD

**Issue by chihtaw** [hpsim/OGL#144]
The `send_offsets `and `recv_offsets ` returned by the function `compute_scatter_from_owner `are of the size equal to `comm->size()`

The expected size should be `comm->size() + 1`

Run the unit test `compute_scatter_from_owner_counts_single_owner` to find out more details.

_Originally posted by @chihta-wang in https://github.com/hpsim/OGL/issues/143#issuecomment-2227922643_

**Comment by greole** [comment]
Addressed by [5ac1a0f](https://github.com/hpsim/OGL/pull/140/commits/5ac1a0ffa88a2863ac39321052b1237573d71f1a)
