### ISSUE TITLE
licence file

### ISSUE THREAD

**Issue by CyrilleBonamy** [hpsim/OGL#57]
I think it can be very beneficial if OGL has a license file.
So automatic tools can detect that OGL is a GNU GPL library (if I'm not wrong)
example : https://kandi.openweaver.com/c++/greole/OGL#Summary

**Comment by CyrilleBonamy** [comment]
It looks fine.  👍

**Comment by greole** [comment]
Thanks for bringing it up. I just merged it into the dev branch.
