### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by maciekhebda** [hpsim/OGL#67]
Hi i have compilation issue, GINGKO is compiling fine, however compilation of OGL produces errors. I tried different OF (OF 6, OF 8, OF10, OFv2106, OF2206) Always it causes similar error messages full log in attachemnt :
```
/root/OpenFOAM/-8/platforms/linux64GccDPInt32Opt/include/ginkgo/core/base/utils_helper.hpp:215:58: error: static assertion failed: p must be an rvalue for this function to work
  215 |     static_assert(std::is_rvalue_reference<decltype(p)>::value,
      |                                                          ^~~~~
```
I tried both GCC and CLANG compilers.
[makelog.txt](https://github.com/hpsim/OGL/files/9859880/makelog.txt)

**Comment by greole** [comment]
Hi @maciekhebda, 
thanks for the information. Could you provide some more on how you compile things, cmake command, which branch, compiler etc.

**Comment by greole** [comment]
Could you try if the multi_gpu branch works for you?
